# Numpy

Numpy is uses pre-compiled C code to speed-up number processing in python.
With numpy, python can be many times faster and memory-efficient than normal

In [2]:
import numpy as np
np.__version__

'1.26.1'

## Numpy Arrays

Numpy offers powerful and efficient arrays, with the simple syntax of regular python

### Creating Numpy Arrays

In [3]:
np.array([1,2,3,4]) # np.array() receives a list as parameter and returns a numpy array

array([1, 2, 3, 4])

Numpy arrays are much more efficient than python lists, but are strongly typed and can't be modified
It's optimal use is with numbers (int and float), althoug it can receive strings and object

You can specify the data type using the **dtype** parameter in np.array() (the default is int64)

In [5]:
np.array([1,2,3,4]).dtype

dtype('int64')

In [7]:
np.array([1,2,3,4], dtype = 'float').dtype #same values, but diferent types

dtype('float64')

### Multidimensional Arrays

Numpy can create multidimensional arrays (or matrices), by simply passing a regular matrix as parameter in the array() method

In [8]:
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

You can easily access lines, elements and even collumns in this matrix

In [9]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a[0] #line

array([1, 2, 3])

In [10]:
a[0,0] #element

1

In [11]:
a[:, 0] #collumn, using slicing

array([1, 4, 7])

You can also use tridimensional arrays, and even more

In [17]:
b = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
b[:, :, 0]

array([[1, 3],
       [5, 7]])

## Operations With Arrays

One of the most powerful features of numpy, allows you to sum, subtract, divide and multiple arrays by any number and even by each other

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a + 10 #sum

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
a - 10 #subtraction

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

In [23]:
a * 10 #multiplication

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [24]:
a / 10 #division

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [26]:
a + a #sum of two matrices

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [27]:
a * a #multiplication of two matrices

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [28]:
a ** a #power of two matrices

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

You can even use logic operators

In [30]:
a > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [31]:
a % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [35]:
(a * a) <= (a + a)

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

With this, you can basically filter any array by a condition

In [36]:
a[a % 2 == 1] #every odd number in a

array([1, 3, 5, 7, 9])

### Array methods

Numpy has many pre-built methods with arrays, such as:

In [37]:
a.sum() #sum of every element in array

45

In [38]:
a.mean() #mean of every element

5.0

In [39]:
a.std() #standart deviation of array

2.581988897471611

In [41]:
a.var() #variance of array

6.666666666666667

In [ ]:
## Conclusion

Numpy is basically this. There's still a lot of methods and details within numpy, but the the core is 